# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
theme_color:
  enable: true
  main: "#1976D2"
  paginator: "#6190E8" # 分页
  button_hover: "#115293"
  text_selection: "#6190E8"
  link_color: "#333333"
  meta_color: '#2C2C2C'
  hr_color: "#333333"
  read-mode-bg_color: '#F5F5D5'
  inline-code-color: '#333333'

# Main menu navigation
# format: xxx: /xxx/||icon
# ---------------
menu:
  Home: /||fa fa-home
  Archives: /archives/||fa fa-archive
  # Tags: /tags/||fa fa-tags
  # Categories: /categories/||fa fa-folder-open
  # Link: /link/||fa fa-link
  # About: /about/||fa fa-heart
  GitHub: https://github.com/LOUSANPANG||fa fa-github
  Speak: https://github.com/LOUSANPANG/lousanpang.github.io/issues||fa fa-coffee


# Favicon
# ---------------
favicon: /img/favicon.ico

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: true
#   manifest: /img/pwa/manifest.json
#   theme_color: "#fff"
#   apple_touch_icon: /img/pwa/apple-touch-icon.png
#   favicon_32_32: /img/pwa/32.png
#   favicon_16_16: /img/pwa/16.png
#   mask_icon: /img/pwa/safari-pinned-tab.svg
#   shortcut_icon: /img/favicon.ico


# Highlight theme
# ---------------
highlight_theme: light
highlight_copy: true #代碼複製按鈕
highlight_lang: true #代碼語言顯示
highlight_shrink: false #代碼框不展開，需點擊 '>' 打開

code_word_wrap: false

# social settings
# formal: 
#   icon: link
# ---------------
# social:
  # fa fa-github: https://github.com/LOUSANPANG
  # fa fa-rss: /atom.xml

####    search 搜索    -------------------------------------------------------------------------------------------
# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 6

  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# Please see doc for more details: https://jerryc.me/posts/21cfbf15/#本地搜索
# ---------------
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

# ------------------------------------------------------------------------------------------------------------------
# MathJax markdown计算公式
# Please see doc for more details: https://jerryc.me/posts/21cfbf15/#MathJax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# KaTeX markdown计算公式
# ---------------
katex:
  enable: false
  cdn:
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css  
  hide_scrollbar: true

# ----------------------------------------------------------------------------------------------------------------
####   Analysis    ####
# ---------------
# baidu_analytics: 

#Google Analytics
google_analytics:


# stylesheets loaded in the <head>
# ---------------
stylesheets:
  - /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
  - /js/utils.js
  - /js/main.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # fontawesomeV5: https://use.fontawesome.com/releases/v5.8.1/css/all.css
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    js-cookies: https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js

# Post info settings 文章设置
# -----------------------------------------------------------------------------------------------------------------
# avatar: /img/avatar.png
avatar: /img/avatar.jpeg

# the banner image of index
# if the banner of another page not setting,it will show the top_img
top_img: /img/top_img.jpeg

#the banner image of post
# if the post not set the post cover and post top image, it will show it
post_img: /img/post_img.jpeg

# the default cover of the post
default_cover: /img/default_cover.jpeg

# the banner image of archive page
archive_img: /img/archive_img.jpeg

# if the photo link cannot connect,it will show that
lodding_bg:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

post_meta:
  date_type: both # both or created or updated 文章日期是创建日或者更新日或都显示
  categories: true # or false 是否显示分类
  tags: true # or false 是否显示标签

# Please see doc for more details: https://jerryc.me/posts/21cfbf15/#字数统计
wordcount:
  enable: false

# 章节目录
toc:
  enable: true
  number: true

# 自动打开侧边栏
auto_open_sidebar:
  enable: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 自动换行
auto_excerpt:
  enable: true
  length: 150


####    Share System 分享    ####
# ---------------------------------------------------------------------------------------------------------------------------
addThis:
  enable: false
  pubid:

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq

# https://www.addtoany.com/
addtoany:
  enable: false
  item:
    - facebook
    - twitter
    - wechat
    - sina_weibo
    - facebook_messenger
    - email
    - copy_link

####   Comments System 评论    ####
# ---------------------------------------------------------------------------------------------------------------------------
# disqus:
#   enable: false
#   shortname: 
  
# laibili:
#   enable: false
#   uid:

# gitment
#   enable: false
#   owner: 
#   repo: 
#   client_id: 
#   client_secret: 

# gitalk:
#   enable: false
#   client_id: 7eaaa676d6599b89fdaa
#   client_secret: 6f5aeb2ec151eff387732b5d8d2622ab3d258da0
#   repo: https://github.com/LOUSANPANG/lousanpang.github.io
#   owner: LOUSANPANG
#   admin: Lou Guanghao
####   Using this js for redirect to gitalk container after login
####   See https://github.com/gitalk/gitalk/issues/125
#   js: https://cdn.jsdelivr.net/gh/upupming/gitalk@36368e5dffd049e956cdbbd751ff96c28d8255cf/dist/gitalk.min.js

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is true
  appId: 95a9R9VBnOH4DwyKMPbEFN7e-gzGzoHsz # leancloud application app id
  appKey: gAuNuYlxMU3vt0Ea0OJrfbcr # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 6 # comment list page size
  avatar: wavatar # gravatar style https://valine.js.org/#/avatar
  lang: en # i18n: zh-cn/en
  placeholder: 离线请留言 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail #valine comment header inf

#####     Footer Settings 底部信息    ####
# -------------------------------------------------------------------------------------------------------------------------
since: 2018

footer_custom_text: If you know me please follow me or leave me a message.

footer_copyright:
  enable: true

ICP:
  enable: false
  url: 
  text:


####    站长统计   #### https://github.com/LOUSANPANG
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/webmaster/
bing_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification: 725b13ee7d59bc97f5a2ca424005998c

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:


# 友情鏈接界面設置 
Flink:
  headline: 友情链接
  info_headline: 个人简介
  name: My name is Lou Guanghao
  address: If this project helped you please Give a ⭐️ or follow me to leave a message.  

# 打賞按鈕
reward:
  enable: false
  QR_code:
    - itemlist:
        img: /img/wechat.jpg
        text: 微信
    - itemlist:
        img: /img/alipay.jpg
        text: 支付宝

# 推薦文章
related_post:
  enable: false
  limit: 3 # 顯示推薦文章數目

####    美化/效果    ####
#-------------------------------------------------------------------------------------------------------------------------------------------

# 設置網站背景
# 可設置圖片 或者 顔色
# 圖片格式 background: url(http://xxxxxx.com/xxx.jpg)
# 顔色 background: '#49B202'
# 留空 顯示白色
background:

# footer是否顯示圖片背景(與top_img一致)
footer_bg: false


# canvas_ribbon 禁止彩帶背景
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false

# 動態彩帶
canvas_ribbon_piao:
  enable: false

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: true
  color: '25,118,210' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.6 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  script: https://cdn.jsdelivr.net/gh/jerryc127/CDN/js/canvas-nest.js # or /js/third-party/canvas-nest.js

# 打字效果
activate_power_mode:
  enable: false

# 鼠標點擊效果
fireworks:
  enable: false

# 頭像會一直轉圈
avatar_effect: false

# 網站顯示模式
# day 默認模式
# night 黑暗模式（不建議）
display_mode: day

# 美化post頁顯示
post_beautify:
  enable: false
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

# 全局字體
font:
  enable: false
  font-family: Lato, Helvetica Neue For Number, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, PingFang SC, Hiragino Sans GB,"Microsoft JhengHei", "MicrMicrosoft YaHei", Helvetica Neue, Helvetica, Arial, sans-serif
  code-font: consolas, Menlo, "PingFang SC", "Microsoft JhengHei","Microsoft YaHei", monospace, Helvetica Neue For Number

# 網站名字字體
# 左上角網站名字 主頁居中網站名字
blog_title_font: 
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web #字體鏈接
  font-family: Titillium Web, PingFang SC, Hiragino Sans GB, "Microsoft JhengHei", "Microsoft YaHei", Helvetica Neue, Helvetica, Arial, sans-serif

# 水平分隔綫
hr:
  enable: true
  icon: '\f21c' #fontawesome上圖標的Unicode
  icon-top: -20px

# 主頁subtitle
# 打字效果
subtitle: 
  enable: true
  sub1: I have a dream.
  sub2: Learn quality articles learn the most suitable technology. #如果有符號 ' ，記得前面加上 \ 




####    侧边栏    ####
#------------------------------------------------------------------------------------------------------------------------------------------------
# 側邊欄顯示設置
aside:
  position: right # left or right
  card_author: true
  card_announcement: true # 公告
  card_recent_post: false # 最近文章
  card_categories: true # 分类
  card_tags: true # 标签
  card_archives: false # 档案
  card_webinfo: false # 网站资讯

# 網站公告
announcement:
  content: I have written a two-year blog on Projects + Issues on GitHub and have moved to this.

# busuanzi count for PV / UV in site
# 訪問人數
busuanzi:
  site_uv: true
  site_pv: false
  page_pv: false

# 網頁開通時間
# 格式: 月/日/年 時間
# 也可以寫成 年/月/日 時間
runtimeshow:
  enable: true
  start_date: 3/13/2018 00:00:00


####   右下角按鈕  ####
#---------------------------------------------------------------------------------------------------------------------------------------------------------
# 簡繁轉換
translate:
  enable: false
  # 默認按鈕顯示文字
  default: 繁
  #网站默认语言，1: 繁體中文, 2: 简体中文
  defaultEncoding: 2
  #延迟时间,若不在前, 要设定延迟翻译时间, 如100表示100ms,默认为0
  translateDelay: 0
  #博客网址
  cookieDomain: "https://lousanpang.github.io/"
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: "繁"
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: "简"

# 夜間模式
nightshift:
  enable: true

#閲讀模式
readmode:
  enable: true


####    其他     ####
#-----------------------------------------------------------------------------------------------------------------------------------------------------------

#百度推送
baidu_push:
  enable: false

# https://instant.page/
# prefetch預加載
instantpage:
  enable: true

# Note (Bootstrap Callout)
# https://muse.theme-next.org/docs/tag-plugins/note
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# 圖片懶加載
lazyload:
  enable: true
  script: https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js

# 避免重複網址分散seo
canonical: true

# 禁止百度轉碼
disable_baidu_transformation: true

# twitter分享自動帶上樣式
# https://i.loli.net/2019/09/08/qm3RfvUCKbct1Wz.png
twitter_meta: true

# facebook QQ 等 分享自動帶上樣式
# https://i.loli.net/2019/09/08/2wbFJEKloisRvhj.png
Open_Graph_meta: true
